### ISSUE TITLE
Error executing - C++

### ISSUE THREAD

**Issue by Spo-oky** [AlexanderBabansky/RTMP2NDI#1]
Hi,

I'm trying the release but when I start, it appears a error.

![image](https://user-images.githubusercontent.com/51725018/102633273-1e7ea880-4148-11eb-8c4d-ac6fdd5bf458.png)

Is there something missing that I have to install?

Tks!

**Comment by AlexanderBabansky** [comment]
Fixed. Removed Qt. Check new release.
